Bootstrap: docker
From: centos:7

# sudo singularity build ogs.simg Singularity

%environment
  PATH=/opt/conda/bin:$PATH
  export PATH
  #source /scif/apps/devtools-4/scif/environment.sh


%files
  #devtools-4.scif
  #ogs-base.scif
  #mpi-2_1_1.scif
  #ogs-petsc.scif
  full.scif

%post
  yum install -y wget bzip2 git curl
  wget --quiet https://repo.continuum.io/miniconda/Miniconda3-4.3.31-Linux-x86_64.sh -O miniconda.sh
  /bin/bash miniconda.sh -b -p /opt/conda || true
  rm -f ~/miniconda.sh
  /opt/conda/bin/conda clean -tipsy
  export PATH=/opt/conda/bin:$PATH

  git clone -b fix/environment https://www.github.com/vsoch/scif || true
  cd scif
  python setup.py install
  cd ..

  #pip install scif
  #scif install /devtools-4.scif
  #scif install /ogs-base.scif
  #scif install /mpi-2_1_1.scif
  #scif install /ogs-petsc.scif
  scif install /full.scif

  mkdir -p /sw /scratch /projects

%runscript
  scif "$@"
