Bootstrap: docker
From: centos:7

# sudo singularity build ogs.simg Singularity

%environment
  PATH=/opt/conda/bin:$PATH
  export PATH
  source /scif/apps/devtools-4/scif/environment.sh

%files
  devtools-4.scif
  ogs-base.scif

%post
  yum install -y wget bzip2 git curl
  wget --quiet https://repo.continuum.io/miniconda/Miniconda3-4.3.31-Linux-x86_64.sh -O ~/miniconda.sh
  /bin/bash ~/miniconda.sh -b -p /opt/conda
  rm -f ~/miniconda.sh
  /opt/conda/bin/conda clean -tipsy

  /opt/conda/bin/pip install scif
  /opt/conda/bin/scif install /devtools-4.scif
  /opt/conda/bin/scif install /ogs-base.scif

%runscript
  scif "$@"
